### ISSUE TITLE
JSON INVALID ERROR

### ISSUE THREAD

**Issue by brothergiez** [dhanifudin/rest-in-ci#3]
An uncaught Exception was encountered
Type: DomainException
Syntax error, malformed JSON
Filename: /var/www/html/apis/application/libraries/JWT.php
Line Number: 358

Help me....

**Comment by dhanifudin** [comment]
~~maybe you send mailformed json, please use linter (e.g jsonlint or [jsonlint.com](jsonlint.com)) to validate your json~~
my mistakes, thanks for report the issue if token can't be decoded. It's fixed now.
