### ISSUE TITLE
Validate token is valid or not

### ISSUE THREAD

**Issue by Siddheshshah89** [dhanifudin/rest-in-ci#4]
Hello,
 Can you please tell how to i check token is valid or not when jwt decode the token?

**Comment by dhanifudin** [comment]
you can use validateToken function in [authorization_helper.php](https://github.com/dhanifudin/rest-in-ci/blob/0f9122d4a747380cc31ee4a02096191b8db9b7fe/application/helpers/authorization_helper.php#L9). Please check this line for [example](https://github.com/dhanifudin/rest-in-ci/blob/0f9122d4a747380cc31ee4a02096191b8db9b7fe/application/controllers/Todo.php#L21)

**Comment by dhanifudin** [comment]
this is the same issue, I'll close it.
